### PR TITLE
Fix/embedding

### LINKED ISSUE #166: Review naming between embedded and embedding

### PR DESCRIPTION
**Pull request by BotellaA**
fix #166

### CODE REVIEW

File: bindings/python/src/model/representation/core/brep.h [hunk 1]
```diff
@@ -101,8 +95,7 @@ namespace geode
             .def( "nb_internal_surface_corners",
                 ( index_t( BRep::* )( const Surface3D& ) const )
                     & BRep::nb_internal_corners )
-            .def(
-                "internal_surface_corners",
```
Comment (mparquer) [inline bindings/python/src/model/representation/core/brep.h]: what about internal corners inside lines?
Also, thanks to the dimensions, we guess that the internal object is the corner but might be more obvious with internal_corners_inside_surface?

File: bindings/python/src/model/representation/core/brep.h [hunk 2]
```diff
@@ -172,82 +161,76 @@ namespace geode
                     return components;
                 },
                 pybind11::return_value_policy::reference )
-            .def( "nb_embedded_corner_surfaces",
+            .def( "nb_embedding_corner_surfaces",
```
Comment (mparquer) [inline bindings/python/src/model/representation/core/brep.h:175]: again, thanks to the respective dimensions, we guess who is embedding who but it is not obvious to which object the adjective is related to. 
one suggestion : embedded_corner_inside_surfaces -> would give the corner
another suggestion: embedding_surfaces_of_corner -> would give the range of surfaces

File: bindings/python/src/model/representation/core/section.h [hunk 3]
```diff
@@ -102,38 +96,35 @@ namespace geode
                     return components;
                 },
                 pybind11::return_value_policy::reference )
-            .def( "nb_embedded_corner_surfaces",
```
Comment (mparquer) [inline bindings/python/src/model/representation/core/section.h:105]: what about embedded corner inside a line? maybe not different from an internal one

File: bindings/python/src/model/representation/core/brep.h (hunk 1 above)
Comment (BotellaA) [reply bindings/python/src/model/representation/core/brep.h]: An internal corner in a ligne is just defining a boundary of two lines. It's our convention. What do you think?

File: bindings/python/src/model/representation/core/brep.h (hunk 2 above)
Comment (BotellaA) [reply bindings/python/src/model/representation/core/brep.h:175]: @panquez an opinion on this? I agree that it is not obvious at all.

File: bindings/python/src/model/representation/core/brep.h (hunk 1 above)
Comment (mparquer) [reply bindings/python/src/model/representation/core/brep.h]: I am ok if we can have make collections of lines. I didn't check.

File: bindings/python/src/model/representation/core/brep.h (hunk 2 above)
Comment (panquez) [reply bindings/python/src/model/representation/core/brep.h:175]: The best name would be nb_embedding_surfaces. But since we cannot overload these functions we should specified on which type of objects they are applied. IMO, Marion's suggestion `embedding_surfaces_of_corner` is the best we can do

Comment (BotellaA) [reply bindings/python/src/model/representation/core/brep.h]: done
