### PR TITLE
fix(AABBTree): refactoring

### LINKED ISSUE #446: Refactor aabb files
Refactor includes, implementation position, ...

### PR DESCRIPTION
**Pull request by BotellaA**
Fix #446

### CODE REVIEW

File: include/geode/geometry/bounding_box.h [hunk 1]
```diff
@@ -56,10 +57,18 @@ namespace geode
 
         bool intersects( const BoundingBox< dimension >& bbox ) const;
 
+        bool intersects( const Ray< dimension >& ray ) const;
+
+        double signed_distance( const Point< dimension >& point ) const;
```
Comment (panquez) [inline include/geode/geometry/bounding_box.h:62]: Add a bit of doc to tell what happens if the point is inside. It is 0, negative?

File: src/geode/geometry/bounding_box.cpp [hunk 2]
```diff
@@ -65,13 +66,161 @@ namespace geode
...
         Point< dimension > max_;
     };
 
+    template <>
+    bool BoundingBox< 3 >::Impl::line_intersects(
+        const InfiniteLine3D& line ) const
+    {
+        const auto box_half_extent = diagonal() / 2.;
+        const auto line_translated_origin = line.origin() - center();
+        const auto orign_cross_direction =
```
Comment (panquez) [inline src/geode/geometry/bounding_box.cpp:184]: origin?

**Review by panquez — APPROVED** [review]

**Review by MelchiorSchuh — APPROVED** [review]
